MPESA_CONSUMER_KEY: '<FA3Du8vUzcfGHDGQnLcK6GnwmIQPr1Dk>'
MPESA_CONSUMER_SECRET: '<h4xNt2BFAG2uoRLY>'
MPESA_PASSKEY: '<bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919>'
MPESA_SHORTCODE: '174379'
MPESA_INITIATOR_NAME: 'testapi'
MPESA_INITIATOR_PASSWORD: '<Safaricom999!*!>'
CALLBACK_URL: '<ngrok http://127.0.0.1:3000>'
REGISTER_URL: "https://sandbox.safaricom.co.ke/mpesa/c2b/v1/registerurl"